# Generated by Django 4.0.4 on 2022-05-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture_Hall_Name', models.CharField(max_length=25)),
                ('Occupancy_status', models.CharField(max_length=20)),
                ('hall_id', models.IntegerField()),
            ],
        ),
    ]
